### ISSUE TITLE
details of the format

### ISSUE THREAD

**Issue by wojdyr** [gjbekker/cif-parsers#1]
Hi, I just came across mmJSON and I really like it (a similar idea called CIF-JSON was discussed recently on [cif-developers][1] mailing list).
Could you add more details to the documentation? For example, the current example doesn't show how `.` and `?` are represented in mmJSON. Or maybe it's already documented somewhere?

[1]: http://www.iucr.org/__data/iucr/lists/cif-developers/

**Comment by gjbekker** [comment]
Thank you for your question and sorry for my late reply.

The `.` and `?` CIF values are both handled as `null` values in mmJSON since unfortunately `undefined` is not available in JSON. I have updated the README.md to include this information. I have also included some examples to how to convert the mmCIF files to mmJSON files.

**Comment by gjbekker** [comment]
In case you are interested, I have also prepared a simple cif->json converter demo:
https://pdbj.org/tools/cif2json

Here, you can load your cif file, then by clicking on "Convert", the CIF data will be converted to JSON, which you can then save to your local hard drive.

**Comment by wojdyr** [comment]
Thank you!
I was asking because I wanted to modify [gemmi-convert][1] so that it can output mmJSON, and I used your converter as a reference.
I plan to evaluate this format further in the future. We may find it useful for some internal applications. I'll probably come back with more questions in a couple of months.


[1]: https://github.com/project-gemmi/gemmi/
